### ISSUE TITLE
Damage from Zelda (?) even though she is still trapped in chest

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zsxd#43]
In the final room, Link takes damage from an invisible enemy (Zelda ?) when near the closed chest. Dying does only trigger the game over screen. Opening the chest and being beaten to death still triggers the ending screen though.

**Comment by christopho** [comment]
Fixed by https://github.com/christopho/solarus/commit/d2de2de02c7721e261572fab6583c972141577a4, thanks
