### ISSUE TITLE
Wrong font size in options pause submenu

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zsxd#44]
(Despite havng tested the game prior to the 1.5 release, there is one visual bug i actually missed since I never changed the buttons)

In the options submenu, the font is displayed in a larger size than it should be and overlaps the other fields in the key mapping columns.

I already found the cause : in pause_option.lua,  the font size parameter is neither retrieved from the sol.main.get_menu_font() return, nor applied to any of the text fields.

Unless it is volontary, this will be easy to fix

**Comment by christopho** [comment]
Thanks for the report!
